#113 - move post request to factory
VamosJuntas/vamosjuntas pull request #139
Opened 2017-01-27 10:58 UTC by pedrro

Extraí para uma factory, mas está dando esse erro: 
`http://localhost:3001/reports net::ERR_CONNECTION_REFUSED`

O mesmo erro acontece na master, vamos verificar?

2017-01-29 13:58 UTC, viniciusgama requested changes

2017-01-29 13:58 UTC, viniciusgama commented on www/js/controller/report.address.controller.js
> +angular.module('vamosJuntas').controller('ReportAddressController', ['$scope', '$stateParams', '$location', '$ionicHistory', 'reportFactory', function($scope, $stateParams, $location, $ionicHistory,
acho que vale por umas quebras de linha aqui para facilitar a leitura, o que acham?

2017-01-29 13:58 UTC, viniciusgama commented on www/js/factory/report.factory.js
> +        return reportObject;
tava pensando que ao invés de fazer:
```
reportObject.createReport = createReport;
return reportObject;
```

poderiamos usar:

```
return {
   createReport: createReport
}

```

acho que isso ajuda a deixar mais claro qual a interface publica do objeto, fica mais explicito o que ele tá expondo.

2017-01-29 14:01 UTC, viniciusgama commented
@pedrro esse problema `http://localhost:3001/reports net::ERR_CONNECTION_REFUSED` deve ser porque a API não esta rodando. Ou vc não startou o stubby, para isso rode o `npm run start-stubby`. Para entender melhor sobre a ferramenta, olhe aqui https://github.com/mrak/stubby4node

2017-01-30 13:01 UTC, pedrro commented on www/js/factory/report.factory.js
> +        return reportObject;
Acho que a gente poderia adicionar isso como débito técnico, pois todas as factories precisam ser refatoradas para serviços, o @ebragaparah estava planejando fazer isso, o que acha?

2017-01-30 17:17 UTC, viniciusgama approved these changes

2017-01-30 17:19 UTC, viniciusgama requested changes

2017-01-30 17:19 UTC, viniciusgama commented on package.json
> +    "start-stubby": "node_modules/stubby/bin/stubby -q -s 3001 -l localhost -d ./stubs/reports.yml"
@pedrro não precisa referenciar o binario no `package.json`, o npm já faz isso pra vc se a dependência estiver listada.

2017-01-30 19:01 UTC, pedrro commented on package.json
> +    "start-stubby": "node_modules/stubby/bin/stubby -q -s 3001 -l localhost -d ./stubs/reports.yml"
Verdade, tinha tentado uma vez, mas tinha dado uma treta, voltei e agora deu!

2017-01-30 20:22 UTC, viniciusgama approved these changes

2017-01-30 20:22 UTC, viniciusgama commented
LGTM. Pode mergear se quiser.

2017-01-30 21:30 UTC, merged